
<!-- application/views/scripts/partials/pagination.phtml -->
<div class="pagination">
    <?php if ($this->previous): ?>
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo; Anterior</a>
    <?php endif; ?>
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        <?php else: ?>
            <strong><?php echo $page; ?></strong>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->next): ?>
        <a href="<?php echo $this->url(array('page' => $this->next)); ?>">Próxima &raquo;</a>
    <?php endif; ?>
</div>