
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Zend Project</title>

         
    </head>

    <body>

        <?php echo $this->render("header.phtml"); ?>
        <div class="jumbotron"><?php echo $this->layout()->content; ?> </div>
        <?php echo  $this->baseUrl() ;?>
    </div> <!-- /container -->
    <?php echo $this->render("footer.phtml"); ?>




</body>
</html>
